# Generated by Django 2.2.26 on 2022-04-06 20:16

import apps.labo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Laboratory1', 'Laboratory_1'), ('Laboratory2', 'Laboratory_2')], default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaboExam',
            fields=[
                ('book_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ward', models.CharField(choices=[('', ''), ('OPD', 'OPD'), ('ANC', 'ANC'), ('MAT', 'Maternity'), ('LW', 'Labour / Delivery'), ('MW', 'Medical Ward'), ('SW', 'Surgical Ward'), ('CW', "Childrens' Ward"), ('OTHER', 'Other')], max_length=20)),
                ('prescriber', models.CharField(blank=True, max_length=15)),
                ('ys', models.CharField(default=apps.labo.models.auto_increment_ys, editable=False, max_length=20, verbose_name='Y-Serial')),
                ('ms', models.CharField(default=apps.labo.models.auto_increment_lms, editable=False, max_length=20, verbose_name='M-Serial')),
                ('ds', models.CharField(default=apps.labo.models.auto_increment_lds, editable=False, max_length=20, verbose_name='D-Serial')),
                ('cost', models.IntegerField(default=0, editable=False)),
                ('paid', models.IntegerField(default='')),
                ('count', models.CharField(editable=False, max_length=7)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='labo.LaboDept')),
            ],
        ),
        migrations.CreateModel(
            name='LaboTestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LaboTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=15, unique=True)),
                ('cost', models.IntegerField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboTestCategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboDept')),
            ],
        ),
        migrations.CreateModel(
            name='LaboStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=17, verbose_name='Phone')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.SlugField(blank=True, default=0, editable=False, max_length=7)),
                ('title', models.CharField(choices=[('Path', 'Pathologist'), ('LAB Sc.', 'Lab. Scientist'), ('LAB TECH', 'Lab. Technician'), ('As.Tech', 'Assistant Technician'), ('Assis', 'Assistant'), ('Other', 'Other')], default='', max_length=15)),
            ],
            options={
                'abstract': False,
                'unique_together': {('Phone', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='LaboPatient',
            fields=[
                ('ln', models.CharField(default=apps.labo.models.auto_increment_ln, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Lab-Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='regi.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='LaboExamItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('cost', models.CharField(editable=False, max_length=6)),
                ('paid', models.CharField(default=0, max_length=6)),
                ('lexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexams', to='labo.LaboExam')),
                ('ltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboTestType')),
            ],
            options={
                'unique_together': {('ltype', 'lexam')},
            },
        ),
        migrations.AddField(
            model_name='laboexam',
            name='labo_type',
            field=models.ManyToManyField(through='labo.LaboExamItem', to='labo.LaboTestType'),
        ),
        migrations.AddField(
            model_name='laboexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboPatient'),
        ),
        migrations.CreateModel(
            name='LaboFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('lab_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboExam')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboExamItem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labo.LaboStaff')),
            ],
            options={
                'unique_together': {('lab_test', 'lab_exam')},
            },
        ),
    ]
