# Generated by Django 2.2.26 on 2022-04-06 20:16

import apps.radi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Echo', 'Echo'), ('Xray', 'Xray')], default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadiStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=17, verbose_name='Phone')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.SlugField(blank=True, default=0, editable=False, max_length=7)),
                ('title', models.CharField(choices=[('RAD', 'Radiologist'), ('RAD TECHNO', 'Rad. Technologist'), ('RAD TECH', 'Rad. Technician'), ('As.Tech', 'Assistant Technician'), ('ASS', 'Assistant'), ('OTHER', 'Other')], default='', max_length=15)),
            ],
            options={
                'abstract': False,
                'unique_together': {('Phone', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='RadiTestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Echo-General', 'Echo-General'), ('Echo Special', 'Echo-Special'), ('Xray-General', 'Xray-General'), ('Xray-Special', 'Xray-Special')], max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiDept')),
            ],
        ),
        migrations.CreateModel(
            name='RadiTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=15, unique=True)),
                ('cost', models.IntegerField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiTestCategory')),
            ],
        ),
        migrations.CreateModel(
            name='UExam',
            fields=[
                ('book_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ward', models.CharField(choices=[('', ''), ('OPD', 'OPD'), ('ANC', 'ANC'), ('MAT', 'Maternity'), ('LW', 'Labour / Delivery'), ('MW', 'Medical Ward'), ('SW', 'Surgical Ward'), ('CW', "Childrens' Ward"), ('OTHER', 'Other')], max_length=20)),
                ('prescriber', models.CharField(blank=True, max_length=15)),
                ('ys', models.CharField(default=apps.radi.models.auto_increment_uys, editable=False, max_length=20, verbose_name='Y-Serial')),
                ('ms', models.CharField(default=apps.radi.models.auto_increment_ums, editable=False, max_length=20, verbose_name='M-Serial')),
                ('ds', models.CharField(default=apps.radi.models.auto_increment_uds, editable=False, max_length=20, verbose_name='D-Serial')),
                ('cost', models.IntegerField(default=0, editable=False)),
                ('paid', models.IntegerField(default=0, editable=False)),
                ('count', models.CharField(editable=False, max_length=7)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='radi.RadiDept')),
            ],
        ),
        migrations.CreateModel(
            name='UExamItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('cost', models.CharField(editable=False, max_length=6)),
                ('paid', models.CharField(default=0, max_length=6)),
                ('uexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uexams', to='radi.UExam')),
                ('utype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiTestType')),
            ],
            options={
                'unique_together': {('utype', 'uexam')},
            },
        ),
        migrations.CreateModel(
            name='XExam',
            fields=[
                ('book_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ward', models.CharField(choices=[('', ''), ('OPD', 'OPD'), ('ANC', 'ANC'), ('MAT', 'Maternity'), ('LW', 'Labour / Delivery'), ('MW', 'Medical Ward'), ('SW', 'Surgical Ward'), ('CW', "Childrens' Ward"), ('OTHER', 'Other')], max_length=20)),
                ('prescriber', models.CharField(blank=True, max_length=15)),
                ('ys', models.CharField(default=apps.radi.models.auto_increment_xys, editable=False, max_length=20, verbose_name='Y-Serial')),
                ('ms', models.CharField(default=apps.radi.models.auto_increment_xms, editable=False, max_length=20, verbose_name='M-Serial')),
                ('ds', models.CharField(default=apps.radi.models.auto_increment_xds, editable=False, max_length=20, verbose_name='D-Serial')),
                ('cost', models.IntegerField(default=0, editable=False)),
                ('paid', models.IntegerField(default='')),
                ('count', models.CharField(editable=False, max_length=7)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='radi.RadiDept')),
            ],
        ),
        migrations.CreateModel(
            name='XExamItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('cost', models.CharField(editable=False, max_length=6)),
                ('paid', models.CharField(default=0, max_length=6)),
                ('xexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.XExam')),
                ('xtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiTestType')),
            ],
            options={
                'unique_together': {('xtype', 'xexam')},
            },
        ),
        migrations.CreateModel(
            name='XPatient',
            fields=[
                ('xn', models.CharField(default=apps.radi.models.auto_increment_un, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='XR-Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='regi.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='xexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.XPatient'),
        ),
        migrations.AddField(
            model_name='xexam',
            name='x_exam',
            field=models.ManyToManyField(through='radi.XExamItem', to='radi.RadiTestType'),
        ),
        migrations.CreateModel(
            name='UPatient',
            fields=[
                ('un', models.CharField(default=apps.radi.models.auto_increment_un, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='US-Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='regi.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='uexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.UPatient'),
        ),
        migrations.AddField(
            model_name='uexam',
            name='u_exam',
            field=models.ManyToManyField(through='radi.UExamItem', to='radi.RadiTestType'),
        ),
        migrations.CreateModel(
            name='RadiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiStaff')),
                ('x_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.XExam')),
                ('x_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.XExamItem')),
            ],
            options={
                'unique_together': {('x_test', 'x_exam')},
            },
        ),
        migrations.CreateModel(
            name='UFinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiStaff')),
                ('u_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.UExamItem')),
                ('uexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.UExam')),
            ],
            options={
                'unique_together': {('u_test', 'uexam')},
            },
        ),
    ]
