# Generated by Django 2.2.26 on 2022-04-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(default='', max_length=15, unique=True)),
                ('sn', models.IntegerField(default='')),
                ('Properties', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiDept')),
            ],
        ),
        migrations.CreateModel(
            name='RadiMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(default='', max_length=15, unique=True)),
                ('sn', models.IntegerField(default='')),
                ('Properties', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiDept')),
            ],
        ),
        migrations.CreateModel(
            name='RadiHanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night'), ('Straight', 'Straight'), ('10 to', '10 to'), ('Other', 'Other')], max_length=20)),
                ('statistics', models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], max_length=20)),
                ('lines', models.CharField(choices=[('Ruled', 'Ruled'), ('Not Ruled', 'Not Ruled')], max_length=20)),
                ('state1', models.CharField(default='OK', max_length=50)),
                ('state2', models.CharField(default='OK', max_length=50)),
                ('state3', models.CharField(default='OK', max_length=50)),
                ('state4', models.CharField(default='OK', max_length=50)),
                ('state5', models.CharField(default='OK', max_length=50)),
                ('state6', models.CharField(default='OK', max_length=50)),
                ('other1', models.CharField(default='OK', max_length=20)),
                ('other2', models.CharField(default='OK', max_length=20)),
                ('other3', models.CharField(default='OK', max_length=20)),
                ('remarks', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiDept')),
                ('device1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device1', to='radi.RadiEquipment')),
                ('device2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device2', to='radi.RadiEquipment')),
                ('device3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device3', to='radi.RadiEquipment')),
                ('machine1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine1', to='radi.RadiMachine')),
                ('machine2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine2', to='radi.RadiMachine')),
                ('machine3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine3', to='radi.RadiMachine')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radi.RadiStaff')),
            ],
        ),
    ]
