# Generated by Django 2.2.26 on 2022-04-06 20:16

import apps.phar.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(choices=[('STORE', 'Store'), ('DISPENSARY', 'Dispensary')], default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharDrugCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharDrugType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=30)),
                ('strength', models.CharField(default='', max_length=30)),
                ('form', models.CharField(choices=[('tabs', 'Tablets'), ('Syrop', 'Syrop'), ('Sach', 'Sachet')], default='', max_length=30)),
                ('unit_cost', models.IntegerField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharDrugCategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharDept')),
            ],
            options={
                'unique_together': {('type_name', 'strength', 'form')},
            },
        ),
        migrations.CreateModel(
            name='PharPatient',
            fields=[
                ('pn', models.CharField(default=apps.phar.models.auto_increment_pdpn, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Phar-Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='regi.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharPrescription',
            fields=[
                ('book_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ward', models.CharField(choices=[('', ''), ('OPD', 'OPD'), ('ANC', 'ANC'), ('MAT', 'Maternity'), ('LW', 'Labour / Delivery'), ('MW', 'Medical Ward'), ('SW', 'Surgical Ward'), ('CW', "Childrens' Ward"), ('OTHER', 'Other')], max_length=20)),
                ('prescriber', models.CharField(blank=True, max_length=15)),
                ('ys', models.CharField(default=apps.phar.models.auto_increment_pys, editable=False, max_length=20, verbose_name='Y-Serial')),
                ('ms', models.CharField(default=apps.phar.models.auto_increment_pdms, editable=False, max_length=20, verbose_name='M-Serial')),
                ('ds', models.CharField(default=apps.phar.models.auto_increment_pdds, editable=False, max_length=20, verbose_name='D-Serial')),
                ('cost', models.IntegerField(default=0, editable=False)),
                ('paid', models.IntegerField(default='')),
                ('difference', models.IntegerField(default=0, editable=False)),
                ('count', models.CharField(editable=False, max_length=7)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharDept')),
            ],
        ),
        migrations.CreateModel(
            name='PharUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PharStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=17, verbose_name='Phone')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.SlugField(blank=True, default=0, editable=False, max_length=7)),
                ('title', models.CharField(choices=[('PHARM', 'Pharmacist'), ('PHA TECHNO', 'Pha. Technologist'), ('PHA TECH', 'Pha. Technician'), ('As.Tech', 'Assistant Technician'), ('ASS', 'Assistant'), ('OTHER', 'Other')], default='', max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('Phone', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='PharPrescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('cost', models.IntegerField(editable=False)),
                ('paid', models.IntegerField(default=0)),
                ('difference', models.IntegerField(default=0, editable=False)),
                ('ph_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharDrugType')),
                ('ph_presc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharPrescription')),
            ],
            options={
                'unique_together': {('ph_presc', 'ph_drug')},
            },
        ),
        migrations.AddField(
            model_name='pharprescription',
            name='drug_name',
            field=models.ManyToManyField(through='phar.PharPrescriptionItem', to='phar.PharDrugType'),
        ),
        migrations.AddField(
            model_name='pharprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharPatient'),
        ),
        migrations.CreateModel(
            name='PharDrugDispensed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_doze', models.CharField(default=0, max_length=6)),
                ('times_per_day', models.CharField(choices=[('', ''), ('1/D', 'Once/Day'), ('2/D', 'Twice/Day'), ('3/D', 'Thrice/Day'), ('4', 'Four/D'), ('Q4', 'Every 4H'), ('Q6', 'Every 6H'), ('Q8', 'Every 8H'), ('Q12', 'Every 12H')], default=0, max_length=6)),
                ('duration_in_days', models.CharField(default=0, max_length=15)),
                ('instructions', models.TextField(blank=True, max_length=150, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('phar_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharPrescriptionItem')),
                ('phar_presc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharPrescription')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phar.PharStaff')),
            ],
            options={
                'unique_together': {('phar_drug', 'phar_presc')},
            },
        ),
    ]
