# Generated by Django 2.2.26 on 2022-04-06 20:16

import apps.regi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=13)),
                ('last_name', models.CharField(blank=True, max_length=13)),
                ('full_name', models.CharField(max_length=27, unique=True)),
                ('address', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=17, unique=True, verbose_name='Phone')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('reg_num', models.CharField(max_length=10, unique=True, verbose_name='Register No')),
                ('sn', models.CharField(default=apps.regi.models.auto_increment_sn, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Serial No')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30)),
                ('ds', models.CharField(default='auto_increment_ds', max_length=20, verbose_name='D-Serial')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegiStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=17, verbose_name='Phone')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.SlugField(blank=True, default=0, editable=False, max_length=7)),
                ('title', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
                'unique_together': {('Phone', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('CONST', 'consultation'), ('RDV', 'rendez-vous'), ('VISIT', 'visit'), ('OTHER', 'other')], max_length=30)),
                ('ds', models.CharField(default=apps.regi.models.auto_increment_ds, editable=False, max_length=20, verbose_name='D-Serial')),
                ('ms', models.CharField(default=apps.regi.models.auto_increment_ms, editable=False, max_length=20, verbose_name='M-Serial')),
                ('cons_book', models.CharField(choices=[('0', 'N/C'), ('500', '500'), ('1000', '1000'), ('1500', '1500')], max_length=8)),
                ('fees', models.CharField(choices=[('0', 'N/C'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('5000', '5000'), ('10000', '10000'), ('5500', '5500'), ('12000', '12000'), ('15000', '15000')], max_length=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regi.Patient')),
            ],
        ),
    ]
