# Generated by Django 2.2.26 on 2022-04-06 20:16

import apps.cons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phar', '0001_initial'),
        ('radi', '0001_initial'),
        ('regi', '0001_initial'),
        ('labo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cons1', 'Consultation_1'), ('Cons2', 'Consultation_2')], default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsPatient',
            fields=[
                ('cn', models.CharField(default=apps.cons.models.auto_increment_cn, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Con-Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(default='none', on_delete=django.db.models.deletion.CASCADE, to='regi.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain', models.CharField(max_length=150)),
                ('past_med_history', models.CharField(max_length=250)),
                ('fees', models.CharField(max_length=12)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cons.ConsPatient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('book_num', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ward', models.CharField(choices=[('', ''), ('OPD', 'OPD'), ('ANC', 'ANC'), ('MAT', 'Maternity'), ('LW', 'Labour / Delivery'), ('MW', 'Medical Ward'), ('SW', 'Surgical Ward'), ('CW', "Childrens' Ward"), ('OTHER', 'Other')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('prescriber', models.CharField(blank=True, max_length=15)),
                ('temp', models.CharField(max_length=7)),
                ('bp_L', models.CharField(max_length=12)),
                ('bp_R', models.CharField(blank=True, max_length=12)),
                ('pulse_L', models.CharField(max_length=7)),
                ('pulse_R', models.CharField(blank=True, max_length=7)),
                ('satO2', models.CharField(max_length=4)),
                ('other', models.CharField(blank=True, max_length=30)),
                ('cons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cons.Consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cons.Consultation')),
                ('echo', models.ManyToManyField(blank=True, related_name='echo_set', to='radi.RadiTestType')),
                ('labs', models.ManyToManyField(blank=True, to='labo.LaboTestType')),
                ('xray', models.ManyToManyField(blank=True, related_name='xray_set', to='radi.RadiTestType')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=50)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('cons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cons.Consultation')),
                ('ph_drug', models.ManyToManyField(to='phar.PharDrugType')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyes', models.CharField(blank=True, max_length=100)),
                ('mouth', models.CharField(blank=True, max_length=100)),
                ('head', models.CharField(blank=True, max_length=100)),
                ('lungs', models.CharField(blank=True, max_length=100)),
                ('heart', models.CharField(blank=True, max_length=100)),
                ('abdomen', models.CharField(blank=True, max_length=100)),
                ('upperLimbs', models.CharField(blank=True, max_length=100)),
                ('lowerLimbs', models.CharField(blank=True, max_length=100)),
                ('others', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('cons', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cons.Consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE')], max_length=7)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=17, verbose_name='Phone')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code', models.SlugField(blank=True, default=0, editable=False, max_length=7)),
                ('title', models.CharField(choices=[('Path', 'Pathologist'), ('LAB Sc.', 'Lab. Scientist'), ('LAB TECH', 'Lab. Technician'), ('As.Tech', 'Assistant Technician'), ('Assis', 'Assistant'), ('Other', 'Other')], default='', max_length=15)),
            ],
            options={
                'abstract': False,
                'unique_together': {('Phone', 'first_name')},
            },
        ),
    ]
