# Generated by Django 2.2.26 on 2022-04-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('1', 'RDV1P'), ('2', 'POTRJ'), ('3', 'XZHDS'), ('4', 'FIBQN'), ('5', '32JKS')], default='', max_length=5, unique=True)),
                ('duration', models.DurationField(max_length=50)),
            ],
        ),
    ]
